// Copyright 2021 Blues Inc.  All rights reserved.
// Use of this source code is governed by licenses granted by the
// copyright holder including that found in the LICENSE file.

#pragma once

#include <stdbool.h>
#include "stm32wlxx.h"
#include "main.h"
#include "stm32wlxx_ll_gpio.h"

// Code generated by STM32CubeMX does not support BSP
// In order to use BSP, users can add the BSP files in the IDE project space
// and define USE_BSP_DRIVER in the preprocessor definitions
#if defined(USE_BSP_DRIVER)
#include "stm32wlxx_nucleo.h"
#include "stm32wlxx_nucleo_radio.h"
#endif

